### PR TITLE
feat: add `chrome.action` mv3

### PR DESCRIPTION
**Pull request by Yash-Singh1**
Adds the MV3 `chrome.action` chrome extension API and adds `group` and `ungroup` to `chrome.tabs`.

### CODE REVIEW

**Comment by fikstoday** [comment]
Now we await merge completion.
What would be PR turn-around??

**Review by vaibhavhrt — APPROVED** [review]

**Comment by vaibhavhrt** [comment]
@Yash-Singh1 thanks for the PR. Sorry about the delay, I was quite busy last few days. You can open PRs for adding rest of the APIs too, I will try and merge them sooner now. I will also open PRs to add some of the new APIs.

**Comment by vaibhavhrt** [comment]
@Yash-Singh1 also if you have any suggestions for structuring the code better please let me know. As you must have already noticed that adding any new auto-completion is quite a lot of work and needs changes in various files.
I am trying to find ways so that we can add completion providers in a more robust ways instead of hard coding everything. Then we may also we able to write a script to scrape all APIs docs from the chrome website and create a JSON file from it, so that updating the extension will require minimal work.

**Comment by vaibhavhrt** [comment]
For now the PR is merged, but the new APIs you added won't be available on the extension we have on visual studio store. I will make a release later, once we have added all the new APIs.

**Comment by Yash-Singh1** [comment]
> @Yash-Singh1 also if you have any suggestions for structuring the code better please let me know. As you must have already noticed that adding any new auto-completion is quite a lot of work and needs changes in various files.
> 
> I am trying to find ways so that we can add completion providers in a more robust ways instead of hard coding everything. Then we may also we able to write a script to scrape all APIs docs from the chrome website and create a JSON file from it, so that updating the extension will require minimal work.

Yeah, I was thinking of that too, maybe like a GitHub action cron job that updates the Json often.

**Pull request merged**
